# Generated by Django 5.1.3 on 2024-11-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=200)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
