# Generated by Django 5.1.3 on 2024-11-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuarios",
            new_name="Usuario",
        ),
    ]
